ci: ignore inside github actions

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,15 +1,20 @@
 #!/bin/bash
 
-echo -e "===\n>> Pre-push Hook: Checking branch name..."
-
-BRANCH=`git rev-parse --abbrev-ref HEAD`
-PROTECTED_BRANCHES="^(auto-release)"
-
-if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+if [[ -z "${GITHUB_ACTION}" ]]
 then
-  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
+  
+  echo -e "===\n>> Pre-push Hook: Checking branch name..."
+
+  BRANCH=`git rev-parse --abbrev-ref HEAD`
+  PROTECTED_BRANCHES="^(auto-release)"
+
+  if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+  then
+    echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
+  fi
+
+  echo -e ">> Finish checking branch name..."
+
+  exit 0
 fi
 
-echo -e ">> Finish checking branch name..."
-
-exit 0
